### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [avassem85/pymoodo#1]
Hi,

I have looked through your source code - it looks like you are using just the REST endpoints in the Moodo API.

Is there any chance of also integrating the WebSocket API to step away from cloud polling and move toward cloud pushing?

[Moodo Socket.io WebSocket Demo Environment](https://ws.moodo.co:9090/)

**Comment by avassem85** [comment]
I added websocket support see #2. It work standalone. Now I have to create a new component for Home Assistant because the old one is deprecated.

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for this!

Happyy to help / test the HA component if you need?
